version: '3.1'
services:
  app:
    image: "ritagaeta/decidim-roadsteamer:latest"
    volumes:
      - .:/code
    environment:
      - PORT=3000
      - DATABASE_HOST=192.168.1.77
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=ADMIN
      - RAILS_ENV=development
      - RAILS_LOG_TO_STDOUT=1
    ports:
      - 3000:3000
    links:
      - pg
    command: /code/docker/init.sh
  pg:
    image: postgres
    ports: 
     - 5000:5432 
    volumes:
         - pg-data:/var/lib/postgresql/data
    environment:
     - POSTGRES_HOST_AUTH_METHOD=trust
volumes:
  pg-data: {}
